---
title: "Combine eQTLs with matched ATAC-seq data"
author: "Dr Jacob Househam"
date: "24/06/2021"
output: html_document
---

```{r library}
library(data.table);library(matrixStats)
```

## Compile tumour phylogenetic data
```{r filter_eqtl_data}
# Load phylogenetic data
tinfo <- readRDS('input_files/pgls.infotrees.rds')
genedf <- readRDS('input_files/gene_clustering_and_id_conversion.rds')
genedf <- genedf[which(genedf$Group!=4),]

# Compile phylogenetic data
phylosig <- as.data.frame(matrix(0L,nrow=nrow(genedf),ncol=length(tinfo$patients)));row.names(phylosig) <- row.names(genedf)
colnames(phylosig) <- tinfo$patients
for(pat in tinfo$patients) {
  readRDS(paste0('results/',pat,'_lambda_data.rds'))
  resdf <- resdf[row.names(genedf),]
  sigdf <- resdf[which(resdf$LamPval<0.05),]
  phylosig[row.names(sigdf),pat] <- 1
}

# Save phylogenetic tumour dataframe
saveRDS(phylosig,'results/compile_phylo_results.rds')
```

## Load eQTL data and combine with ATAC-seq
```{r combine_eqtl_and_ATAC}
# Load subclonal Enh eQTL results with HW recurrence data added
enhmut <- readRDS('results/enh_subclonal_eqtls.rds')



```
